### ISSUE TITLE
steer adjustment question?

### ISSUE THREAD

**Issue by coolKeen** [navoshta/behavioral-cloning#2]
Hi, I am interested in that how do you decided the steer adjustment(in your code,0.25) for left and right image?Thanks in advanced!

**Comment by alexstaravoitau** [comment]
Hey @coolKeen! I'm not 100% sure I'm afraid, since this was a while ago, but I vaguely remember experimenting with various values and settling on those that performed best. I don't think I spent too much time on this though, so these might not be optimal values — feel free to experiment a bit more, you might as well get some improvement!
